version: 0.0
os: linux
files:
    - source: /docker-compose.yaml
      destination: /home/ubuntu/aws-server-test/docker-compose.yaml
    - source: /.env
      destination: /home/ubuntu/aws-server-test
file_exists_behavior: OVERWRITE

permissions:
    - object: /home/ubuntu
      pattern: '**'
      owner: root
      group: root

hooks:
    AfterInstall:
        - location: scripts/after_deploy.sh
          timeout: 100  
          runas: root